2019-05-21 16:55:49,988 [Thread-7: 140426597435136]/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/core/handlers/exception.py: handle_uncaught_exception: 118 ERROR - Internal Server Error: /api/v1.0/service/weather/
Traceback (most recent call last):
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    result = middleware.process_request(request)
  File "/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/middleware/cache.py", line 128, in process_request
    if request.method not in ('GET', 'HEAD'):
AttributeError: 'Weather' object has no attribute 'method'
2019-05-21 16:55:50,175 [Thread-7: 140426597435136]/home/zhang/python/.virtualenvs/django2.0/lib/python3.6/site-packages/django/core/servers/basehttp.py: log_message: 124 ERROR - "POST /api/v1.0/service/weather/ HTTP/1.1" 500 84927
